### ISSUE TITLE
Unable to open application interface in browser on PC

### ISSUE THREAD

**Issue by ShardOfTheMonolith** [getaurora/download#1]
I have been using this app for more than 1 year. Every time I open the app, the app interface shows up in Chrome. Recently the application interface has not appeared, and the application interface cannot be displayed by clicking to open the application in the taskbar. The app has been updated to version 2.7.11. Windows 10 version is 21H1.

**Comment by ShardOfTheMonolith** [comment]
After uninstalling the app and reinstalling the problem still occurs.

**Comment by lanrui5797** [comment]
> After uninstalling the app and reinstalling the problem still occurs.

Did you resolved the issue? I met the same issue.

**Comment by ShardOfTheMonolith** [comment]
> > After uninstalling the app and reinstalling the problem still occurs.
> 
> Did you resolved the issue? I met the same issue.

Actually, I didn't resolve the issue. It just went well on some day after I created the issue.
