### ISSUE TITLE
用户登录异常，附有Debug日志，开发者麻烦看一下

### ISSUE THREAD

**Issue by 420313439** [getaurora/download#24]
<img width="898" alt="Screenshot 2023-02-24 at 10 52 02 AM" src="https://user-images.githubusercontent.com/16334986/221080570-c2137bd1-f610-4c09-ab20-cd80ae17af07.png">
<img width="1007" alt="Screenshot 2023-02-24 at 9 49 36 AM" src="https://user-images.githubusercontent.com/16334986/221080602-64b7cf80-aa62-468d-acf9-71f5fbae4b46.png">

**Comment by zu-zhi** [comment]
mac M1 遇见同样的问题，求解决

**Comment by iemsoft** [comment]
估计是被封掉了，我这边也是这样子。

**Comment by figo050518** [comment]
我也是，麻烦开发者重视起来，早点解决。

**Comment by Complexification** [comment]
我也遇到同样的问题，其他电脑能用。我 reset 了自己的电脑还是不能用，新提示是“系统维护中”。究竟什么回事？

**Comment by zgzyh** [comment]
我也是，遇到相同问题，麻烦管理员尽快修复。
