### ISSUE TITLE
怎么申请退款

### ISSUE THREAD

**Issue by anicolor** [getaurora/download#241]
有退款成功的吗？刚买了一年会员，电脑端连不上

**Comment by 13612687938** [comment]
啥时候分享VIP给我用用

**Comment by yuntai1006** [comment]
都跑路了，还想退款？

我都换成这个了：[魔法上网](https://github.com/xiaoming2028/FreePAC/wiki/2023%E5%B9%B4%E7%A8%B3%E5%AE%9A%E5%A5%BD%E7%94%A8%E7%9A%84SSR%5CV2Ray%5CTrojan%E6%9C%BA%E5%9C%BA%E6%8E%A8%E8%8D%90%E4%B8%8E%E8%AF%84%E6%B5%8B-%7C-%E6%94%AF%E6%8C%81ChatGPT%E6%B3%A8%E5%86%8C)

**Comment by 13612687938** [comment]
@anicolor 现在是没问题了吗？
