### ISSUE TITLE
安卓版一直系统校验失败3.06还是3.07都不行

### ISSUE THREAD

**Issue by zch133** [getaurora/download#28]
我手机是vivo nex s,手机软件版本号PD1805_A_9.8.21,不管用什么方式只要启动就卡在14%那个界面然后失败.

**Comment by CIELPHAN1** [comment]
这个我有时也遇得到，过一两天就好了。

**Comment by ztbb123** [comment]
请问楼主解决了么？我也是一模一样的这个问题，已经5、6天了

**Comment by gahg96** [comment]
magic os 7.0操作系统，3.0.7VPN软件，搞了一周了，不知道出啥问题了。
[【金山文档】 WechatIMG1104
https://kdocs.cn/l/ceJSy6ivnNJf](url)
【金山文档】 WechatIMG1103
https://kdocs.cn/l/cbUOciFMyW21

**Comment by gahg96** [comment]
https://arr013.network/download/ 手机上这个网址访问不了

**Comment by gurecn** [comment]
经验证，aurora-v2.7.15-1.apk与aurora-2.7.12-Setup-1.exe可用，可下载这个版本试一下。
https://github.com/getaurora/download/releases?page=2

**Comment by ztbb123** [comment]
好像修复了，我现在电脑和手机都可以用了

**Comment by zch133** [comment]
修复了
