### ISSUE TITLE
是跑路了？VIP能退吗？

### ISSUE THREAD

**Issue by jacinthrab** [getaurora/download#33]
![Uploading 1677578656531..jpg…]()
一周啦，客户不回应，邮箱不回复，跑路了！?
VIP不过如此……

**Comment by ltziscj** [comment]
先用2.7.12版本 我看前面帖子说的 因为我手机版也能用 ，所以应该没跑路

**Comment by gurecn** [comment]
经验证，aurora-v2.7.15-1.apk与aurora-2.7.12-Setup-1.exe可用，可下载这个版本试一下。
https://github.com/getaurora/download/releases?page=2

**Comment by Lian1998** [comment]
我是通过重启路由器解决的

**Comment by jacinthrab** [comment]
我退回2712版本，可以连接。但希望最新版本可以修复不能使用的问题。
