### ISSUE TITLE
安卓手机如何使用极光？

### ISSUE THREAD

**Issue by Jacky-Lee466** [getaurora/download#60]
手头的几部安卓手机安装了极光3.0.6以及3.0.7后，运行都是校验系统信息停在14% 之后就是校验失败，尝试了几次都是这样，请问如何解决安卓手机客户端的使用问题呢?

**Comment by cuiyuc** [comment]
> 手头的几部安卓手机安装了极光3.0.6以及3.0.7后，运行都是校验系统信息停在14% 之后就是校验失败，尝试了几次都是这样，请问如何解决安卓手机客户端的使用问题呢?

降级回之前的2版本可以用

**Comment by Jacky-Lee466** [comment]
> > 手头的几部安卓手机安装了极光3.0.6以及3.0.7后，运行都是校验系统信息停在14% 之后就是校验失败，尝试了几次都是这样，请问如何解决安卓手机客户端的使用问题呢?
> 
> 降级回之前的2版本可以用

感谢~！ 安装了2.7.15-1就可以使用了
